# Generated by Django 4.1.5 on 2023-01-06 16:42

import apps.products.services.utils
import apps.products.services.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120)),
                ('barcode', models.CharField(max_length=18, unique=True, validators=[django.core.validators.MinLengthValidator(6), apps.products.services.validators.DigitValidator()])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5)])),
                ('amount', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to=apps.products.services.utils.ImageHandler.path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])])),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
