# Generated by Django 4.1.5 on 2023-01-06 19:55

import apps.products.services.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(height_field=720, upload_to=apps.products.services.utils.ImageHandler.path, validators=[django.core.validators.validate_image_file_extension], width_field=1280),
        ),
    ]
