# Generated by Django 4.1.5 on 2023-01-06 20:45

import apps.products.services.utils
import apps.products.services.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=apps.products.services.utils.ImageHandler.path, validators=[apps.products.services.validators.ImageValidator(0.8), django.core.validators.validate_image_file_extension]),
        ),
    ]
