# Generated by Django 4.1.5 on 2023-01-26 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
