# Generated by Django 4.1.5 on 2023-01-26 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={},
        ),
    ]
